### ISSUE TITLE
Committing more code during review

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/week5-timeToFly#15]
Please don't commit during code review time.

1. It makes it hard for the reviewer as things change when they refresh the repo (potentially invalidating an issue they may have been writing about a lack of tests 😉)
1. You're supposed to be reviewing another team—this is one of the most valuable learning opportunities of the week so it's not fair on them to use this time for your own project instead

**Comment by jokosanyang** [comment]
Noted. :)
