### ISSUE TITLE
Request library should be a production dependency

### ISSUE THREAD

**Issue by oliverjam** [FAC-Sixteen/week5-timeToFly#16]
https://github.com/FAC-Sixteen/week5-timeToFly/blob/c5b6f47a36b310fec4f3145156a151bf10479eb3/package.json#L23

Your server won't work when you deploy it to something like Heroku, since that will do a production install (which doesn't install `devDependencies`). This means you won't have access to the `request` library there.

Anything your server needs while it's running (pretty much anything you `require` in your actual code) should be in `dependencies`)

**Comment by oliverjam** [comment]
(this is probably why your app is down on Heroku FYI: it hit the `require("request")` and couldn't find it)

**Comment by jokosanyang** [comment]
Thanks! Could NOT figure out why Heroku was not having it. Easy fix.
